### ISSUE TITLE
Makefile for 'main_static' is failing

### ISSUE THREAD

**Issue by LaironSk** [HenriqueBBrum/DINT#11] opened 2023-08-11 02:45 UTC
I have issues when running:

./run_experiments.sh microbursts ~/Documents/DINT/results/ 100 0.1 5

```
100
0.1
microbursts
Running microbursts experiment
Min push time is: 0.1
105
P4C_ARGS is --p4runtime-files build/.p4.p4info.txt
sudo mn -c
rm -f *.pcap
rm -rf build pcaps logs
P4C_ARGS is --p4runtime-files build/.p4.p4info.txt
mkdir -p build pcaps logs
p4c-bm2-ss --p4v 16 --p4runtime-files build/main_static.p4.p4info.txt -o build/main_static.json main_static.p4
../utils/Makefile:61: recipe for target 'main_static.json' failed
```

It has to do with my dependencies or it is the makefile itself?

**Comment by HenriqueBBrum** [comment] 2023-08-14 18:30
Hi, I've followed the steps outlined in the README to reproduce my paper's experiments and managed to run the experiments successfully. This error indicates a problem with P4 itself since the BMv2 switch with the 'main_static' code is not being built correctly. I've found some links regarding this problem: [https://github.com/p4lang/tutorials/issues/139](https://github.com/p4lang/tutorials/issues/139) and [https://github.com/p4lang/tutorials/issues/425](https://github.com/p4lang/tutorials/issues/425), hope they are of help.

**Comment by HenriqueBBrum** [comment] 2023-08-29 15:02
Closing this issue.

**Comment by HenriqueBBrum** [comment] 2023-09-04 18:15
Hi, I've found the problem and updated the README. The old README was missing the installation tutorial for the "simple_switch_grpc" executable.

**Closed as completed** 2023-09-25 18:24 UTC
